# Generated by Django 2.2.3 on 2019-08-08 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acereadymade_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0005_auto_20190806_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=250)),
                ('l_name', models.CharField(max_length=250)),
                ('Company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('Country', models.PositiveSmallIntegerField(choices=[(1, 'Nepal'), (1, 'India'), (1, 'Bangladesh')])),
                ('street_add', models.CharField(max_length=250)),
                ('apartment', models.CharField(max_length=250, null=True)),
                ('Town', models.CharField(max_length=250)),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'Kathmandu'), (1, 'Lalitpur'), (1, 'Bhaktapur')])),
                ('postcode', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=250)),
                ('information', models.CharField(blank=True, max_length=500, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acereadymade_app.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
