# Generated by Django 2.2.3 on 2019-08-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Company_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Town',
            new_name='town',
        ),
    ]
