# Generated by Django 2.2.3 on 2019-08-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20190808_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='apartment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
